<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Warez Market Backend</title>
</head>
<body>


<?php if(count($errors) > 0): ?>
    <ul>
    <?php foreach($errors as $error): ?>
        <li><?= $error; ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>

<form action="/admin/login" method="POST">
    <input type="text"      name="email"    value="<?= htmlspecialchars($email); ?>"      placeholder="email@example.com"/>
    <input type="password"  name="password" value="<?= htmlspecialchars($password); ?>"   placeholder="password"/>
    <input type="hidden"    name="token"    value="<?= $token; ?>"/>
    <input type="submit"    name="submit"   value="Log In"/>
</form>
</body>
</html>
