        
        <!-- Navigation START -->

        <a href="/admin/dashboard" title="Link to homepage">Home</a>
        <a href="/admin/logout" title="Link to homepage">Log out</a>
        <a href="/admin/categories" title="Link to homepage">Categories</a>
        <a href="/admin/products" title="Link to homepage">Products</a>
        <a href="/admin/orders" title="Link to homepage">Orders</a>

        <!-- Navigation END -->